### ISSUE TITLE
deep_wantarray?

### ISSUE THREAD

**Issue by tobyink** [CindyLinz/Perl-Return-Deep#1]
Seems like it would be useful.

**Comment by CindyLinz** [comment]
Sounds good. Now, there should be two versions of it. One for deep_ret, and the other for sym_ret. (thinking...)

**Comment by CindyLinz** [comment]
I did it~~

**Comment by CindyLinz** [comment]
version 1.5

**Comment by tobyink** [comment]
Yep, I noticed. It looks like a good module.

**Comment by CindyLinz** [comment]
Thank you~~^^
